FROM python:3.11

RUN mkdir -p /home/app

RUN groupadd app && useradd -g app app

ENV APP_HOME=/home/app/api
RUN mkdir -p $APP_HOME
WORKDIR $APP_HOME

COPY . $APP_HOME
RUN pip install -r requirements-dev.txt
RUN pip install -e .

RUN chown -R app:app $APP_HOME
USER app

CMD ["uvicorn","marketpy.app:app","--host=0.0.0.0","--port=8000","--reload"]